// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carsafa.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Vin { get; set; }

    public int Year { get; set; }

    public int MakeId { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public string Type { get; set; }

    public override string ToString()
    {
       return $"{Vin} {Year} {Make.Make1} {Model} {Color} {Type}";
    }
    public virtual Make Make { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}