// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carsafa.Models;

public partial class Make
{
    public int MakeId { get; set; }

    public string Make1 { get; set; }

    public string Ceo { get; set; }

    public int FoundedYear { get; set; }

    public string Website { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}