// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carsafa.Models;

public partial class Purchase
{
    public int PurchaseId { get; set; }

    public int OwnerId { get; set; }

    public int CarId { get; set; }

    public string PurchaseDate { get; set; }

    public string SaleDate { get; set; }

    public virtual Car Car { get; set; }

    public virtual Owner Owner { get; set; }
}