// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_EF.Models;

public partial class Registration
{
    public int RegistrationId { get; set; }

    public int CourseId { get; set; }

    public int StudentId { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual Student Student { get; set; }
}