// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadDatabase.Models;

public partial class Car
{
    public Car()
    {
        Purchases = new HashSet<Purchase>();
    }
    public int CarId { get; set; }

    public string Vin { get; set; }

    public int Year { get; set; }

    public int MakeId { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public string Type { get; set; }
    public Car(CarInput carinput) : this()
    {
        Vin = carinput.VIN;
        Year = carinput.Year;
        Model = carinput.Model;
        Color = carinput.Color;
        Type = carinput.Type;
    }
    public override string ToString()
    {
        return $" {Vin} {Year} {Make.Make1} {Model} {Color} {Type}";
    }

    public virtual Make Make { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}