// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadDatabase.Models;

public partial class Make
{
    public int MakeId { get; set; }

    public string Make1 { get; set; }

    public string Ceo { get; set; }

    public int FoundedYear { get; set; }

    public string Website { get; set; }


    public Make()
    {
        Cars = new HashSet<Car>();
    }
    public Make(MakeInput makeinput)
    {
        //MakeId = makeinput.MakeID;
        Make1 = makeinput.make;
        Ceo = makeinput.CEO;
        FoundedYear = makeinput.Founded;
        Website = makeinput.Website;
    }

    public override string ToString()
    {
        return $" {Make1} {Ceo} {FoundedYear} {Website}";
    }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}