// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrudData.Models;

public partial class Make
{
    public int MakeId { get; set; }

    public string Make1 { get; set; }

    public string Ceo { get; set; }

    public int FoundedYear { get; set; }

    public string Website { get; set; }

    public override string ToString()
    {
        return $"{Make1} {Ceo} {FoundedYear} {Website}";
    }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();
}