// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_CRUD.Models;

public partial class Dog
{
    public Dog()
    {
        DogToys = new HashSet<DogToy>();
    }

    public Dog(DogInput doginput) : this()
    {
        //Id = doginput.Id;
        Name = doginput.Name;
        Breed = doginput.Breed;
        Image = doginput.Image;
        OwnerId = doginput.OwnerId;
    }
    public int Id { get; set; }

    public string Name { get; set; }

    public string Breed { get; set; }

    public string Image { get; set; }

    public int? OwnerId { get; set; }
    public override string ToString()
    {
        return $"{Name} is a {Breed} owned by {OwnerId}";
    }

    public virtual ICollection<DogToy> DogToys { get; set; } = new List<DogToy>();

    public virtual Owner Owner { get; set; }
}