// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_CRUD.Models;

public partial class Owner
{
    public Owner()
    {
        Dogs = new HashSet<Dog>();
    }
    public Owner(OwnerInput owner) : this()
    {
        //Id = owner.ID;
        Name = owner.Name;
        Image = owner.Image;
    }
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }
    public override string ToString()
    {
        return Name;
    }
    public virtual ICollection<Dog> Dogs { get; set; } = new List<Dog>();
}