// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Database_CRUD.Models;

public partial class SoonerCoContext : DbContext
{
    public SoonerCoContext()
    {
    }

    public SoonerCoContext(DbContextOptions<SoonerCoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Dog> Dogs { get; set; }

    public virtual DbSet<DogToy> DogToys { get; set; }

    public virtual DbSet<Owner> Owners { get; set; }

    public virtual DbSet<Toy> Toys { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=tcp:s26.winhost.com;Initial Catalog=DB_128040_fullaccess;Persist Security Info=True;User ID=DB_128040_fullaccess_user;Password=Mis3033;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Dog>(entity =>
        {
            entity.ToTable("Dog");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Breed)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Image)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");

            entity.HasOne(d => d.Owner).WithMany(p => p.Dogs)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("FK_Dog_Owner");
        });

        modelBuilder.Entity<DogToy>(entity =>
        {
            entity.ToTable("DogToy");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DogId).HasColumnName("DogID");
            entity.Property(e => e.ToyId).HasColumnName("ToyID");

            entity.HasOne(d => d.Dog).WithMany(p => p.DogToys)
                .HasForeignKey(d => d.DogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DogToy_Dog");

            entity.HasOne(d => d.Toy).WithMany(p => p.DogToys)
                .HasForeignKey(d => d.ToyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DogToy_Toy");
        });

        modelBuilder.Entity<Owner>(entity =>
        {
            entity.ToTable("Owner");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Image)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Toy>(entity =>
        {
            entity.ToTable("Toy");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Image)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}